### ISSUE TITLE
Failed to open HCI user channel

### ISSUE THREAD

**Issue by sandangel** [sklins/BlueMoon#7]
I installed lxqt deskop on Arch linux. Use Kwin as window manager, NetworkManager and nm-tray-git. when I start Bluemoon from command line it has an error 
$ bluemoon            
Bluemoon configuration utility ver 5.43
Failed to open HCI user channel 
Is that because I'm not using connman ?

**Comment by ghost** [comment]
The command is `blue_moon` not `bluemoon`, on archlinux there's another package without the underscore ;-)

I suggest a better name like: lxqt_bluemoon

**Comment by Hasanansari24** [comment]
Bluemoon configuration utility ver 5.79
Failed to open HCI user channel
What is this?
